### ISSUE TITLE
Examples of permissions per object

### ISSUE THREAD

**Issue by sgaseretto** [taoufik07/django-graphene-permissions#1]
I couldn't figure it out how to use it to implement permissions per object. Can you provide some examples of queries and mutations based on permissions per object?
Like a simple project manager where where a manager can add user stories to a project and to sprints and the rest of the members only can see the user stories from the current sprint, and a user can be the manager of one project, and a member in another one

**Comment by taoufik07** [comment]
What you're asking for your "simple project", it's more related to the conceptions of your models.

To check permissions for an object inherit from `PermissionDjangoObjectType` and define a static method `permission_classes` that should return a list of permission classes that are going to be applied to the Object.

```python
# other imports
from django_graphene_permissions import PermissionDjangoObjectType
from django_graphene_permissions.permissions import IsAuthenticated

from .custom_permissions import IsStaff

class ExampleNode(PermissionDjangoObjectType):
    class Meta:
        model = Example
        interfaces = (relay.Node,)
        filter_fields = ['id']

    @staticmethod
    def permission_classes():
        return [IsStaff, IsAuthenticated]

```

**Comment by firasalkafri** [comment]
@taoufik07 this is not working anymore, get_node is not being called

**Comment by taoufik07** [comment]
@firasalkafri just tried it and it's working for me, can you provide some example ?
